### ISSUE TITLE
Support for environment variables instead of GCS_KEY file

### ISSUE THREAD

**Issue by dapeduu** [adonisjs/drive-gcs#2]
## Why this feature is required (specific use-cases will be appreciated)?
Everywhere I've searched says that we should avoid using the key config file directly.

## Have you tried any other work arounds?
I was deploying on Heroku, so I tried to manually upload the file for it not to be on git. But this is not very practical.

## Are you willing to work on it with little guidance?
I would love to help with this! :)

**Comment by RomainLanz** [comment]
Hey @dapeduu! 👋🏻 

I don't know where you have looked, but they recommend using a key file inside the `@google-cloud/storage` and Google doc.

If you want to use something else, you can modify the configuration per your needs. We are passing it in the [`new Storage()` constructor](https://github.com/adonisjs/drive-gcs/blob/develop/src/Drivers/Gcs.ts#L64).

**Comment by dapeduu** [comment]
@RomainLanz Thanks for the reply! Indeed, on their docs it says that its recomended. But how should I make the deploy for example? Im struggling with this, since I cannot just let the file on the repo. People on stackoverflow said that its always better to use env vars.

I tried manually upload the file after the deploy, but its probably not ideal. Also tought on extract the config variables to env vars, and generate the file on build.

**Comment by dapeduu** [comment]
@RomainLanz I just searched and found a script to generate the file after build, using env vars. So I guess the problem is solved. Thank you!!!
